package simpleProject.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import simpleProject.model.EmployeeModel;
import simpleProject.model.EmployeeModelExample;

@Mapper
public interface EmployeeRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	long countByExample(EmployeeModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	int deleteByExample(EmployeeModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	int insert(EmployeeModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	int insertSelective(EmployeeModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	List<EmployeeModel> selectByExample(EmployeeModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	EmployeeModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	int updateByExampleSelective(@Param("record") EmployeeModel record, @Param("example") EmployeeModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	int updateByExample(@Param("record") EmployeeModel record, @Param("example") EmployeeModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	int updateByPrimaryKeySelective(EmployeeModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	int updateByPrimaryKey(EmployeeModel record);
}