package simpleProject.model;

import lombok.ToString;

@ToString
public class EmployeeModel {/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.id
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.name
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.sex
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.age
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.address
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.id
	 * @return  the value of employee.id
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.id
	 * @param id  the value for employee.id
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.name
	 * @return  the value of employee.name
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.name
	 * @param name  the value for employee.name
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.sex
	 * @return  the value of employee.sex
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.sex
	 * @param sex  the value for employee.sex
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.age
	 * @return  the value of employee.age
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.age
	 * @param age  the value for employee.age
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.address
	 * @return  the value of employee.address
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.address
	 * @param address  the value for employee.address
	 * @mbg.generated  Wed Jan 13 14:02:35 JST 2021
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}
}