package com.simpleproject.model;

public class ProdcutStockModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productstock.warehouses_id
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    private Integer warehousesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productstock.products_id
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    private Integer productsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productstock.stock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    private Integer stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productstock.warehouses_id
     *
     * @return the value of productstock.warehouses_id
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    public Integer getWarehousesId() {
        return warehousesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productstock.warehouses_id
     *
     * @param warehousesId the value for productstock.warehouses_id
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    public void setWarehousesId(Integer warehousesId) {
        this.warehousesId = warehousesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productstock.products_id
     *
     * @return the value of productstock.products_id
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    public Integer getProductsId() {
        return productsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productstock.products_id
     *
     * @param productsId the value for productstock.products_id
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    public void setProductsId(Integer productsId) {
        this.productsId = productsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productstock.stock
     *
     * @return the value of productstock.stock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productstock.stock
     *
     * @param stock the value for productstock.stock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }
}