package com.simpleproject.model;

public class WarehousesModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouses.id
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouses.name
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouses.address
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouses.id
     *
     * @return the value of warehouses.id
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouses.id
     *
     * @param id the value for warehouses.id
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouses.name
     *
     * @return the value of warehouses.name
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouses.name
     *
     * @param name the value for warehouses.name
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouses.address
     *
     * @return the value of warehouses.address
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouses.address
     *
     * @param address the value for warehouses.address
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}