package com.simpleproject.repository;

import com.simpleproject.model.ProductsModel;
import com.simpleproject.model.ProductsModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductsRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    long countByExample(ProductsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    int deleteByExample(ProductsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    int insert(ProductsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    int insertSelective(ProductsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    List<ProductsModel> selectByExample(ProductsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    ProductsModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    int updateByExampleSelective(@Param("record") ProductsModel record, @Param("example") ProductsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    int updateByExample(@Param("record") ProductsModel record, @Param("example") ProductsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    int updateByPrimaryKeySelective(ProductsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Sat Jan 16 22:07:27 JST 2021
     */
    int updateByPrimaryKey(ProductsModel record);
}