package com.simpleproject.repository;

import com.simpleproject.model.ProdcutStockModel;
import com.simpleproject.model.ProdcutStockModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductStockRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    long countByExample(ProdcutStockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    int deleteByExample(ProdcutStockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    int deleteByPrimaryKey(@Param("warehousesId") Integer warehousesId, @Param("productsId") Integer productsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    int insert(ProdcutStockModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    int insertSelective(ProdcutStockModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    List<ProdcutStockModel> selectByExample(ProdcutStockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    ProdcutStockModel selectByPrimaryKey(@Param("warehousesId") Integer warehousesId, @Param("productsId") Integer productsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    int updateByExampleSelective(@Param("record") ProdcutStockModel record, @Param("example") ProdcutStockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    int updateByExample(@Param("record") ProdcutStockModel record, @Param("example") ProdcutStockModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    int updateByPrimaryKeySelective(ProdcutStockModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productstock
     *
     * @mbg.generated Sat Jan 16 22:07:39 JST 2021
     */
    int updateByPrimaryKey(ProdcutStockModel record);
}