package com.simpleproject.repository;

import com.simpleproject.model.WarehousesModel;
import com.simpleproject.model.WarehousesModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WarehousesRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    long countByExample(WarehousesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    int deleteByExample(WarehousesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    int insert(WarehousesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    int insertSelective(WarehousesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    List<WarehousesModel> selectByExample(WarehousesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    WarehousesModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    int updateByExampleSelective(@Param("record") WarehousesModel record, @Param("example") WarehousesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    int updateByExample(@Param("record") WarehousesModel record, @Param("example") WarehousesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    int updateByPrimaryKeySelective(WarehousesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouses
     *
     * @mbg.generated Sat Jan 16 22:09:21 JST 2021
     */
    int updateByPrimaryKey(WarehousesModel record);
}